mode = "dark"

accent = "#fe39dc"
selection = "#4a1340"
muted = "#6e5f63"

background = "#040404"
dark_background = "#030303"
darker_background = "#020202"
lighter_background = "#0f0f0f"

foreground = "#efe5e7"
dark_foreground = "#9d9698"
light_foreground = "#d3c7ca"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(1fe4f6ee) rgba(fe39dcee) 45deg"
hyprland_inactive_border = "rgba(6e5f63aa)"

red = "#fe4335"
yellow = "#ffe97e"
orange = "#fda54a"
green = "#5be809"
cyan = "#1fe4f6"
blue = "#4b7bfd"
magenta = "#fe39dc"
brown = "#7f5325"

bright_red = "#fe8c7c"
bright_yellow = "#fff9de"
bright_green = "#aaff90"
bright_cyan = "#bff7fe"
bright_blue = "#7aa1fd"
bright_magenta = "#fe93e4"
