mode = "light"

accent = "#9f0598"
selection = "#e6c0e1"
muted = "#757665"

background = "#fdfef9"
dark_background = "#f2f2ec"
darker_background = "#e5e5de"
lighter_background = "#ebece3"

foreground = "#0a0a01"
dark_foreground = "#56564a"
light_foreground = "#2e2f23"
bright_foreground = "#020201"

hyprland_active_border = "rgba(05670dee) rgba(9f0598ee) 45deg"
hyprland_inactive_border = "rgba(757665aa)"

red = "#655600"
yellow = "#605802"
orange = "#635701"
green = "#466000"
cyan = "#05670d"
blue = "#005c8e"
magenta = "#9f0598"
brown = "#3b3401"

bright_red = "#544700"
bright_yellow = "#504901"
bright_green = "#394f02"
bright_cyan = "#005405"
bright_blue = "#044c76"
bright_magenta = "#83007e"
