mode = "dark"

accent = "#c6b2ea"
selection = "#3f4356"
muted = "#496973"

background = "#0b181c"
dark_background = "#081215"
darker_background = "#060c0e"
lighter_background = "#19262b"

foreground = "#e0eaed"
dark_foreground = "#95a1a4"
light_foreground = "#c0cdd1"
bright_foreground = "#f7fbfc"

hyprland_active_border = "rgba(90e1e7ee) rgba(c6b2eaee) 45deg"
hyprland_inactive_border = "rgba(496973aa)"

red = "#e6a3a8"
yellow = "#f4dca1"
orange = "#f6bc9b"
green = "#9cdbb9"
cyan = "#90e1e7"
blue = "#7fb9de"
magenta = "#c6b2ea"
brown = "#7b5e4e"

bright_red = "#f9cacd"
bright_yellow = "#fef8ea"
bright_green = "#cdf7df"
bright_cyan = "#d0fbfe"
bright_blue = "#b0d7f0"
bright_magenta = "#e3d6fd"
