mode = "dark"

accent = "#fe32e3"
selection = "#491042"
muted = "#6e5f63"

background = "#030303"
dark_background = "#020202"
darker_background = "#020202"
lighter_background = "#0d0d0d"

foreground = "#efe5e7"
dark_foreground = "#9c9697"
light_foreground = "#d3c7ca"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(1be5eeee) rgba(fe32e3ee) 45deg"
hyprland_inactive_border = "rgba(6e5f63aa)"

red = "#fe423d"
yellow = "#ffe97e"
orange = "#fea54c"
green = "#14eb4d"
cyan = "#1be5ee"
blue = "#2581fe"
magenta = "#fe32e3"
brown = "#7f5326"

bright_red = "#fd8c80"
bright_yellow = "#fff9dc"
bright_green = "#a1ffa7"
bright_cyan = "#b0fbff"
bright_blue = "#6aa5fd"
bright_magenta = "#fe91e9"
