mode = "light"

accent = "#a0028e"
selection = "#e6bee1"
muted = "#7a7274"

background = "#fdfdfd"
dark_background = "#f2f2f2"
darker_background = "#e4e4e4"
lighter_background = "#ebebeb"

foreground = "#0d0809"
dark_foreground = "#5f5155"
light_foreground = "#372a2d"
bright_foreground = "#030102"

hyprland_active_border = "rgba(066166ee) rgba(a0028eee) 45deg"
hyprland_inactive_border = "rgba(7a7274aa)"

red = "#b20211"
yellow = "#655600"
orange = "#834a06"
green = "#05661d"
cyan = "#066166"
blue = "#0053b8"
magenta = "#a0028e"
brown = "#4f2c04"

bright_red = "#94000c"
bright_yellow = "#524601"
bright_green = "#005313"
bright_cyan = "#014f53"
bright_blue = "#004498"
bright_magenta = "#860077"
