mode = "dark"

accent = "#e45cf2"
selection = "#58245d"
muted = "#8b7b80"

background = "#020202"
dark_background = "#010101"
darker_background = "#010101"
lighter_background = "#1a1416"

foreground = "#faf3f5"
dark_foreground = "#b7aaad"
light_foreground = "#e5dbdd"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(15e8d9ee) rgba(e45cf2ee) 45deg"
hyprland_inactive_border = "rgba(8b7b80aa)"

red = "#ff645e"
yellow = "#eddc05"
orange = "#fda440"
green = "#a1db00"
cyan = "#15e8d9"
blue = "#5f9efd"
magenta = "#e45cf2"
brown = "#8b5a23"

bright_red = "#fdaca4"
bright_yellow = "#ffec1d"
bright_green = "#c4fb5e"
bright_cyan = "#92fef2"
bright_blue = "#a2c6fd"
bright_magenta = "#f59ffe"
