mode = "dark"

accent = "#c47ce1"
selection = "#3b2544"
muted = "#6e5f63"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#0f090b"

foreground = "#efe5e7"
dark_foreground = "#948e8f"
light_foreground = "#d3c7ca"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(1be6edee) rgba(c47ce1ee) 45deg"
hyprland_inactive_border = "rgba(6e5f63aa)"

red = "#e3655b"
yellow = "#fee88c"
orange = "#fba658"
green = "#74e086"
cyan = "#1be6ed"
blue = "#4a83e5"
magenta = "#c47ce1"
brown = "#7e532c"

bright_red = "#f49288"
bright_yellow = "#fff9df"
bright_green = "#adfbb7"
bright_cyan = "#affbfe"
bright_blue = "#78a5f0"
bright_magenta = "#dba6f2"
