mode = "dark"

accent = "#ff93e1"
selection = "#5c2e4c"
muted = "#7e5568"

background = "#1c0712"
dark_background = "#15050e"
darker_background = "#0e0409"
lighter_background = "#2b1520"

foreground = "#efe5e9"
dark_foreground = "#a5979e"
light_foreground = "#d3c7cc"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(16eeedee) rgba(ff93e1ee) 45deg"
hyprland_inactive_border = "rgba(7e5568aa)"

red = "#fd93a9"
yellow = "#fedb72"
orange = "#feb994"
green = "#37ef8a"
cyan = "#16eeed"
blue = "#99abfd"
magenta = "#ff93e1"
brown = "#7f5d4a"

bright_red = "#fdc7d1"
bright_yellow = "#fff8e5"
bright_green = "#b9ffcd"
bright_cyan = "#c6fffd"
bright_blue = "#c2cffe"
bright_magenta = "#ffccef"
