mode = "dark"

accent = "#16bb77"
selection = "#08492f"
muted = "#5c8a8c"

background = "#000303"
dark_background = "#000202"
darker_background = "#000101"
lighter_background = "#001b1c"

foreground = "#eff7f7"
dark_foreground = "#a4b1b2"
light_foreground = "#d5e1e1"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(10edf2ee) rgba(16bb77ee) 45deg"
hyprland_inactive_border = "rgba(5c8a8caa)"

red = "#1bb3bc"
yellow = "#90e7fe"
orange = "#60cdde"
green = "#1dd3c0"
cyan = "#10edf2"
blue = "#11abeb"
magenta = "#16bb77"
brown = "#35717a"

bright_red = "#23dde9"
bright_yellow = "#c3f1fe"
bright_green = "#14f8e1"
bright_cyan = "#97fcfe"
bright_blue = "#7ccffe"
bright_magenta = "#54e39b"
