mode = "dark"

accent = "#d68fe4"
selection = "#51385a"
muted = "#5e8895"

background = "#000205"
dark_background = "#000104"
darker_background = "#000102"
lighter_background = "#001a22"

foreground = "#f0f6f9"
dark_foreground = "#a4b0b5"
light_foreground = "#d6e0e3"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(0dd8dcee) rgba(d68fe4ee) 45deg"
hyprland_inactive_border = "rgba(5e8895aa)"

red = "#ee7c8e"
yellow = "#fbc959"
orange = "#fe9f6e"
green = "#52daa6"
cyan = "#0dd8dc"
blue = "#43aef4"
magenta = "#d68fe4"
brown = "#8c573d"

bright_red = "#fea9b3"
bright_yellow = "#fee5b1"
bright_green = "#93f6cb"
bright_cyan = "#78f5f8"
bright_blue = "#8accfd"
bright_magenta = "#efb6fb"
