mode = "light"

accent = "#7a4284"
selection = "#dccfde"
muted = "#787285"

background = "#fdfefc"
dark_background = "#f3f0f9"
darker_background = "#e6e3ec"
lighter_background = "#ede9f5"

foreground = "#0b0615"
dark_foreground = "#57535f"
light_foreground = "#2f2c37"
bright_foreground = "#020103"

hyprland_active_border = "rgba(0c606eee) rgba(7a4284ee) 45deg"
hyprland_inactive_border = "rgba(787285aa)"

red = "#8b3c68"
yellow = "#6a5600"
orange = "#8b4227"
green = "#09625f"
cyan = "#0c606e"
blue = "#3a559c"
magenta = "#7a4284"
brown = "#532817"

bright_red = "#7b2959"
bright_yellow = "#564602"
bright_green = "#06514e"
bright_cyan = "#084f5b"
bright_blue = "#29438c"
bright_magenta = "#6a2f74"
