mode = "dark"

accent = "#fe98ca"
selection = "#4c2e3d"
muted = "#7d5857"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#190405"

foreground = "#f0e5e4"
dark_foreground = "#958e8d"
light_foreground = "#d4c7c6"
bright_foreground = "#fdf9f9"

hyprland_active_border = "rgba(fdc2a3ee) rgba(fe98caee) 45deg"
hyprland_inactive_border = "rgba(7d5857aa)"

red = "#fd9598"
yellow = "#ffd899"
orange = "#fdb995"
green = "#7ce695"
cyan = "#fdc2a3"
blue = "#83b2fd"
magenta = "#fe98ca"
brown = "#7f5d4b"

bright_red = "#fdc8c8"
bright_yellow = "#fef8ee"
bright_green = "#bbffc8"
bright_cyan = "#feeee7"
bright_blue = "#b8d3fc"
bright_magenta = "#fecfe4"
