mode = "dark"

accent = "#fe5c8c"
selection = "#4c1c2a"
muted = "#7d5950"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#190502"

foreground = "#f0e5e2"
dark_foreground = "#958e8c"
light_foreground = "#d4c7c4"
bright_foreground = "#fdf9f8"

hyprland_active_border = "rgba(fdb89aee) rgba(fe5c8cee) 45deg"
hyprland_inactive_border = "rgba(7d5950aa)"

red = "#fc4735"
yellow = "#fee5b7"
orange = "#ffa35e"
green = "#ffaf7c"
cyan = "#fdb89a"
blue = "#ec3060"
magenta = "#fe5c8c"
brown = "#80522f"

bright_red = "#f59282"
bright_yellow = "#fff8eb"
bright_green = "#fddecb"
bright_cyan = "#fce6dc"
bright_blue = "#e6838f"
bright_magenta = "#fe9db2"
