mode = "light"

accent = "#9c3700"
selection = "#e5ccbc"
muted = "#727767"

background = "#fdfefa"
dark_background = "#f1f3ec"
darker_background = "#e4e5df"
lighter_background = "#eaece4"

foreground = "#080b01"
dark_foreground = "#54574b"
light_foreground = "#2c2f24"
bright_foreground = "#020201"

hyprland_active_border = "rgba(03652dee) rgba(9c3700ee) 45deg"
hyprland_inactive_border = "rgba(727767aa)"

red = "#605802"
yellow = "#585c02"
orange = "#5c5a01"
green = "#485f04"
cyan = "#03652d"
blue = "#0a606c"
magenta = "#9c3700"
brown = "#373601"

bright_red = "#504903"
bright_yellow = "#484b00"
bright_green = "#3b4e01"
bright_cyan = "#005423"
bright_blue = "#02505a"
bright_magenta = "#812c00"
