mode = "light"

accent = "#a10295"
selection = "#e5bfe4"
muted = "#857166"

background = "#fcfefe"
dark_background = "#f9f0eb"
darker_background = "#ece2de"
lighter_background = "#f5e8e2"

foreground = "#140501"
dark_foreground = "#5f524c"
light_foreground = "#362b25"
bright_foreground = "#030101"

hyprland_active_border = "rgba(824a04ee) rgba(a10295ee) 45deg"
hyprland_inactive_border = "rgba(857166aa)"

red = "#b30320"
yellow = "#6d5500"
orange = "#884600"
green = "#02670e"
cyan = "#824a04"
blue = "#393de1"
magenta = "#a10295"
brown = "#522a00"

bright_red = "#930519"
bright_yellow = "#594500"
bright_green = "#005308"
bright_cyan = "#6b3c02"
bright_blue = "#3020d6"
bright_magenta = "#84007b"
