mode = "dark"

accent = "#ce6afc"
selection = "#3a1e53"
muted = "#54618c"

background = "#010111"
dark_background = "#01010d"
darker_background = "#010109"
lighter_background = "#050920"

foreground = "#e5e8f0"
dark_foreground = "#9597a2"
light_foreground = "#c6cad5"
bright_foreground = "#f9fafe"

hyprland_active_border = "rgba(8ed5fcee) rgba(ce6afcee) 45deg"
hyprland_inactive_border = "rgba(54618caa)"

red = "#fc4356"
yellow = "#fee799"
orange = "#fda460"
green = "#23dee4"
cyan = "#8ed5fc"
blue = "#3f7efc"
magenta = "#ce6afc"
brown = "#7f5230"

bright_red = "#fe8a8b"
bright_yellow = "#fef9e6"
bright_green = "#87fafe"
bright_cyan = "#d8effd"
bright_blue = "#72a3ff"
bright_magenta = "#dfa0ff"
