mode = "dark"

accent = "#db64ed"
selection = "#421e47"
muted = "#516676"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#030c15"

foreground = "#e1e9ef"
dark_foreground = "#8c9094"
light_foreground = "#c2ccd3"
bright_foreground = "#f7fbfd"

hyprland_active_border = "rgba(1ce6e9ee) rgba(db64edee) 45deg"
hyprland_inactive_border = "rgba(516676aa)"

red = "#fc4353"
yellow = "#fee6a2"
orange = "#fda461"
green = "#9edb11"
cyan = "#1ce6e9"
blue = "#008be3"
magenta = "#db64ed"
brown = "#7f5231"

bright_red = "#ff8a89"
bright_yellow = "#fef8e8"
bright_green = "#c5f978"
bright_cyan = "#a3feff"
bright_blue = "#48abfe"
bright_magenta = "#ef96fd"
