mode = "light"

accent = "#9411a5"
selection = "#e4c2e6"
muted = "#6c767e"

background = "#fefdfc"
dark_background = "#eff2f4"
darker_background = "#e2e5e7"
lighter_background = "#e8ecef"

foreground = "#030a10"
dark_foreground = "#4c575f"
light_foreground = "#252f37"
bright_foreground = "#010203"

hyprland_active_border = "rgba(066263ee) rgba(9411a5ee) 45deg"
hyprland_inactive_border = "rgba(6c767eaa)"

red = "#b30029"
yellow = "#6c5500"
orange = "#884600"
green = "#436003"
cyan = "#066263"
blue = "#055b97"
magenta = "#9411a5"
brown = "#522a00"

bright_red = "#920521"
bright_yellow = "#584501"
bright_green = "#364e00"
bright_cyan = "#015051"
bright_blue = "#014a7d"
bright_magenta = "#7d018d"
