mode = "dark"

accent = "#fe838c"
selection = "#4c272a"
muted = "#6f6149"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#120900"

foreground = "#ece7df"
dark_foreground = "#928f8a"
light_foreground = "#d0cac0"
bright_foreground = "#fcfaf6"

hyprland_active_border = "rgba(39dcaaee) rgba(fe838cee) 45deg"
hyprland_inactive_border = "rgba(6f6149aa)"

red = "#f37e60"
yellow = "#fcca4b"
orange = "#ffa249"
green = "#c5c541"
cyan = "#39dcaa"
blue = "#04b4e9"
magenta = "#fe838c"
brown = "#805125"

bright_red = "#fead97"
bright_yellow = "#fef1d4"
bright_green = "#e4e57f"
bright_cyan = "#82f9cd"
bright_blue = "#69d3ff"
bright_magenta = "#feb9bb"
