mode = "dark"

accent = "#fd6178"
selection = "#62262e"
muted = "#898065"

background = "#030200"
dark_background = "#020100"
darker_background = "#010100"
lighter_background = "#1b1505"

foreground = "#f7f5ef"
dark_foreground = "#b1aea3"
light_foreground = "#e1ded5"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(fec93aee) rgba(fd6178ee) 45deg"
hyprland_inactive_border = "rgba(898065aa)"

red = "#ff6461"
yellow = "#fad60c"
orange = "#fda350"
green = "#d5b604"
cyan = "#fec93a"
blue = "#e08612"
magenta = "#fd6178"
brown = "#8b5a2c"

bright_red = "#fdaca6"
bright_yellow = "#ffe886"
bright_green = "#fad601"
bright_cyan = "#fee5ae"
bright_blue = "#fdb268"
bright_magenta = "#ffa9af"
