mode = "dark"

accent = "#fa4dc8"
selection = "#4b173c"
muted = "#3f6c6e"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#000f10"

foreground = "#dfeaeb"
dark_foreground = "#8a9192"
light_foreground = "#c0cece"
bright_foreground = "#f6fbfb"

hyprland_active_border = "rgba(1be6ecee) rgba(fa4dc8ee) 45deg"
hyprland_inactive_border = "rgba(3f6c6eaa)"

red = "#fe396a"
yellow = "#fee6aa"
orange = "#ffa26c"
green = "#15e6a3"
cyan = "#1be6ec"
blue = "#0c91c9"
magenta = "#fa4dc8"
brown = "#805136"

bright_red = "#f98c99"
bright_yellow = "#fff8e8"
bright_green = "#93fecd"
bright_cyan = "#acfcfe"
bright_blue = "#3db1eb"
bright_magenta = "#f79bd6"
