mode = "dark"

accent = "#f653d5"
selection = "#612051"
muted = "#9c756f"

background = "#050100"
dark_background = "#040100"
darker_background = "#020000"
lighter_background = "#250e0b"

foreground = "#faf3f2"
dark_foreground = "#b7aba8"
light_foreground = "#e6dbd9"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(17e8d9ee) rgba(f653d5ee) 45deg"
hyprland_inactive_border = "rgba(9c756faa)"

red = "#fe6368"
yellow = "#fed076"
orange = "#fea065"
green = "#11e97e"
cyan = "#17e8d9"
blue = "#669cfe"
magenta = "#f653d5"
brown = "#8c5838"

bright_red = "#fdaba8"
bright_yellow = "#fee5b5"
bright_green = "#9cfeba"
bright_cyan = "#92fff2"
bright_blue = "#a4c5fe"
bright_magenta = "#fe9fe6"
