mode = "dark"

accent = "#e949ff"
selection = "#501556"
muted = "#7d5279"

background = "#150114"
dark_background = "#10010f"
darker_background = "#0b010a"
lighter_background = "#240a23"

foreground = "#ede5ec"
dark_foreground = "#a195a0"
light_foreground = "#d0c7cf"
bright_foreground = "#fcf9fc"

hyprland_active_border = "rgba(02e8dfee) rgba(e949ffee) 45deg"
hyprland_inactive_border = "rgba(7d5279aa)"

red = "#fe06ad"
yellow = "#fcee13"
orange = "#fea274"
green = "#92de08"
cyan = "#02e8df"
blue = "#4d7bfd"
magenta = "#e949ff"
brown = "#7f513a"

bright_red = "#ff7ec3"
bright_yellow = "#fffcc7"
bright_green = "#b5ff58"
bright_cyan = "#a3fff8"
bright_blue = "#7aa1fe"
bright_magenta = "#f295fe"
