mode = "dark"

accent = "#d06afa"
selection = "#3e204b"
muted = "#426882"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#000d1c"

foreground = "#e1e9ef"
dark_foreground = "#8c9094"
light_foreground = "#c2ccd3"
bright_foreground = "#f7fbfd"

hyprland_active_border = "rgba(1ce5f2ee) rgba(d06afaee) 45deg"
hyprland_inactive_border = "rgba(426882aa)"

red = "#d951cf"
yellow = "#bff2fe"
orange = "#a5b8fe"
green = "#17e1d6"
cyan = "#1ce5f2"
blue = "#497cfd"
magenta = "#d06afa"
brown = "#535c7f"

bright_red = "#eb87e1"
bright_yellow = "#effbfe"
bright_green = "#7afef4"
bright_cyan = "#b9f8fe"
bright_blue = "#78a1fe"
bright_magenta = "#e19fff"
