mode = "dark"

accent = "#ff6362"
selection = "#612725"
muted = "#6a8a6a"

background = "#000300"
dark_background = "#000200"
darker_background = "#000100"
lighter_background = "#051c07"

foreground = "#f2f7f2"
dark_foreground = "#a8b1a8"
light_foreground = "#d9e0d9"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(00ef99ee) rgba(ff6362ee) 45deg"
hyprland_inactive_border = "rgba(6a8a6aaa)"

red = "#ff673a"
yellow = "#fad60c"
orange = "#ffa32c"
green = "#5fe654"
cyan = "#00ef99"
blue = "#12b98d"
magenta = "#ff6362"
brown = "#8c5a18"

bright_red = "#fead96"
bright_yellow = "#ffe886"
bright_green = "#a6ff9c"
bright_cyan = "#a6ffcc"
bright_blue = "#0ae5ae"
bright_magenta = "#ffaaa4"
