mode = "light"

accent = "#7832b8"
selection = "#ddcaec"
muted = "#6a767f"

background = "#fefdfd"
dark_background = "#eef2f5"
darker_background = "#e1e5e8"
lighter_background = "#e7ecf0"

foreground = "#030a11"
dark_foreground = "#4c575f"
light_foreground = "#252f37"
bright_foreground = "#010203"

hyprland_active_border = "rgba(066263ee) rgba(7832b8ee) 45deg"
hyprland_inactive_border = "rgba(6a767faa)"

red = "#b30615"
yellow = "#685700"
orange = "#844900"
green = "#00661f"
cyan = "#066263"
blue = "#045d88"
magenta = "#7832b8"
brown = "#4f2c00"

bright_red = "#94020e"
bright_yellow = "#554704"
bright_green = "#03541a"
bright_cyan = "#044f51"
bright_blue = "#064c6e"
bright_magenta = "#6912a9"
