mode = "dark"

accent = "#b87bfd"
selection = "#37254c"
muted = "#4f6778"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#010d16"

foreground = "#e1e9ef"
dark_foreground = "#8c9094"
light_foreground = "#c2ccd3"
bright_foreground = "#f7fbfd"

hyprland_active_border = "rgba(1ce6e9ee) rgba(b87bfdee) 45deg"
hyprland_inactive_border = "rgba(4f6778aa)"

red = "#f4524a"
yellow = "#fee88c"
orange = "#ffa44d"
green = "#58e570"
cyan = "#1ce6e9"
blue = "#1090cd"
magenta = "#b87bfd"
brown = "#805227"

bright_red = "#ff8b7f"
bright_yellow = "#fff9e1"
bright_green = "#a3feac"
bright_cyan = "#a2feff"
bright_blue = "#14b0fb"
bright_magenta = "#ceaafe"
