mode = "light"

accent = "#a8164f"
selection = "#e7c4d2"
muted = "#87706a"

background = "#fcfefe"
dark_background = "#faefec"
darker_background = "#ece2df"
lighter_background = "#f6e8e4"

foreground = "#150402"
dark_foreground = "#60524e"
light_foreground = "#372a27"
bright_foreground = "#030101"

hyprland_active_border = "rgba(8d4400ee) rgba(a8164fee) 45deg"
hyprland_inactive_border = "rgba(87706aaa)"

red = "#ac1b18"
yellow = "#7b4f00"
orange = "#8e4100"
green = "#953a02"
cyan = "#8d4400"
blue = "#ac1636"
magenta = "#a8164f"
brown = "#552700"

bright_red = "#940509"
bright_yellow = "#644005"
bright_green = "#7c2f00"
bright_cyan = "#743700"
bright_blue = "#930029"
bright_magenta = "#900040"
