mode = "dark"

accent = "#f1735a"
selection = "#5c2d22"
muted = "#748769"

background = "#010200"
dark_background = "#010100"
darker_background = "#000100"
lighter_background = "#0e1a07"

foreground = "#f3f6f1"
dark_foreground = "#aab0a7"
light_foreground = "#dbe0d8"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(86ed8fee) rgba(f1735aee) 45deg"
hyprland_inactive_border = "rgba(748769aa)"

red = "#e38405"
yellow = "#e3de4f"
orange = "#e9b10e"
green = "#91cc58"
cyan = "#86ed8f"
blue = "#0dbb82"
magenta = "#f1735a"
brown = "#806108"

bright_red = "#fdb16d"
bright_yellow = "#f1ee85"
bright_green = "#b9e98f"
bright_cyan = "#b1feb6"
bright_blue = "#6cdeac"
bright_magenta = "#fdad9c"
