mode = "light"

accent = "#ac054b"
selection = "#e9bfd1"
muted = "#7a7274"

background = "#fdfdfd"
dark_background = "#f2f2f2"
darker_background = "#e4e4e4"
lighter_background = "#ebebeb"

foreground = "#0d0809"
dark_foreground = "#5f5155"
light_foreground = "#372a2d"
bright_foreground = "#030102"

hyprland_active_border = "rgba(983800ee) rgba(ac054bee) 45deg"
hyprland_inactive_border = "rgba(7a7274aa)"

red = "#b2001b"
yellow = "#854700"
orange = "#9a3700"
green = "#b20500"
cyan = "#983800"
blue = "#b20022"
magenta = "#ac054b"
brown = "#5c2100"

bright_red = "#940014"
bright_yellow = "#6e3a00"
bright_green = "#940300"
bright_cyan = "#7d2e00"
bright_blue = "#94001b"
bright_magenta = "#90043e"
