mode = "dark"

accent = "#f051f3"
selection = "#5d1f60"
muted = "#8b769b"

background = "#030106"
dark_background = "#020104"
darker_background = "#010002"
lighter_background = "#1d0f27"

foreground = "#f7f4f9"
dark_foreground = "#b1abb5"
light_foreground = "#e0dce4"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(23e7e1ee) rgba(f051f3ee) 45deg"
hyprland_inactive_border = "rgba(8b769baa)"

red = "#ff58a9"
yellow = "#fed07c"
orange = "#fea083"
green = "#1ce3c0"
cyan = "#23e7e1"
blue = "#938efd"
magenta = "#f051f3"
brown = "#8c5848"

bright_red = "#fea5c9"
bright_yellow = "#ffe4b5"
bright_green = "#85ffe1"
bright_cyan = "#8ffef9"
bright_blue = "#bcbdff"
bright_magenta = "#fe99fe"
