mode = "dark"

accent = "#af80fd"
selection = "#433165"
muted = "#6f80a5"

background = "#000108"
dark_background = "#000106"
darker_background = "#000003"
lighter_background = "#0b152c"

foreground = "#f2f5fb"
dark_foreground = "#a9aeb8"
light_foreground = "#dadee6"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(20e4f7ee) rgba(af80fdee) 45deg"
hyprland_inactive_border = "rgba(6f80a5aa)"

red = "#fa6774"
yellow = "#ffd320"
orange = "#fda15e"
green = "#13e79d"
cyan = "#20e4f7"
blue = "#649dfe"
magenta = "#af80fd"
brown = "#8b5934"

bright_red = "#feaaac"
bright_yellow = "#fee79a"
bright_green = "#94ffca"
bright_cyan = "#b1f6ff"
bright_blue = "#a3c5fe"
bright_magenta = "#cdb5fe"
