mode = "light"

accent = "#6e3bb2"
selection = "#dacdea"
muted = "#6c7587"

background = "#fefdfc"
dark_background = "#eef2fa"
darker_background = "#e1e5ed"
lighter_background = "#e6ebf6"

foreground = "#040817"
dark_foreground = "#505561"
light_foreground = "#292e38"
bright_foreground = "#010203"

hyprland_active_border = "rgba(07616aee) rgba(6e3bb2ee) 45deg"
hyprland_inactive_border = "rgba(6c7587aa)"

red = "#ac1635"
yellow = "#6a5600"
orange = "#8b4500"
green = "#006441"
cyan = "#07616a"
blue = "#1051bc"
magenta = "#6e3bb2"
brown = "#532900"

bright_red = "#930028"
bright_yellow = "#564605"
bright_green = "#065236"
bright_cyan = "#074f56"
bright_blue = "#0040a6"
bright_magenta = "#5f23a2"
