mode = "light"

accent = "#8d3286"
selection = "#dfccdf"
muted = "#677971"

background = "#fafffc"
dark_background = "#edf4f0"
darker_background = "#dfe6e3"
lighter_background = "#e4eee9"

foreground = "#000d07"
dark_foreground = "#4b5952"
light_foreground = "#25312b"
bright_foreground = "#010201"

hyprland_active_border = "rgba(0d6354ee) rgba(8d3286ee) 45deg"
hyprland_inactive_border = "rgba(677971aa)"

red = "#a52838"
yellow = "#5a5b00"
orange = "#804b00"
green = "#01653c"
cyan = "#0d6354"
blue = "#066167"
magenta = "#8d3286"
brown = "#4d2d00"

bright_red = "#930126"
bright_yellow = "#4a4b00"
bright_green = "#005330"
bright_cyan = "#005144"
bright_blue = "#094f53"
bright_magenta = "#7c1976"
