mode = "light"

accent = "#8b27a6"
selection = "#e1c8e7"
muted = "#787285"

background = "#fdfefc"
dark_background = "#f3f0f9"
darker_background = "#e6e3ec"
lighter_background = "#ede9f5"

foreground = "#0b0615"
dark_foreground = "#57535f"
light_foreground = "#2f2c37"
bright_foreground = "#020103"

hyprland_active_border = "rgba(076261ee) rgba(8b27a6ee) 45deg"
hyprland_inactive_border = "rgba(787285aa)"

red = "#b10044"
yellow = "#7c4e01"
orange = "#9d3600"
green = "#346204"
cyan = "#076261"
blue = "#5c3dc6"
magenta = "#8b27a6"
brown = "#5e2000"

bright_red = "#900537"
bright_yellow = "#664005"
bright_green = "#2a5102"
bright_cyan = "#075150"
bright_blue = "#4f25b8"
bright_magenta = "#790294"
