mode = "dark"

accent = "#d06fee"
selection = "#502b5f"
muted = "#85789f"

background = "#020107"
dark_background = "#010105"
darker_background = "#010003"
lighter_background = "#1a1029"

foreground = "#f6f4fa"
dark_foreground = "#afacb6"
light_foreground = "#dfdce5"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(20e7e4ee) rgba(d06feeee) 45deg"
hyprland_inactive_border = "rgba(85789faa)"

red = "#fe5e81"
yellow = "#fece96"
orange = "#fd9f7d"
green = "#8bdf47"
cyan = "#20e7e4"
blue = "#998bff"
magenta = "#d06fee"
brown = "#8b5745"

bright_red = "#fda9b5"
bright_yellow = "#fee3c4"
bright_green = "#b8fc8a"
bright_cyan = "#8cfefb"
bright_blue = "#bfbcfc"
bright_magenta = "#eaa6ff"
