mode = "dark"

accent = "#b77bfe"
selection = "#472f65"
muted = "#7f7aa2"

background = "#020107"
dark_background = "#010105"
darker_background = "#010003"
lighter_background = "#16112b"

foreground = "#f5f4fa"
dark_foreground = "#adacb7"
light_foreground = "#dedde6"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1be5f1ee) rgba(b77bfeee) 45deg"
hyprland_inactive_border = "rgba(7f7aa2aa)"

red = "#fd4fc7"
yellow = "#f8c2fe"
orange = "#fa8fea"
green = "#afc2fc"
cyan = "#1be5f1"
blue = "#36a4ff"
magenta = "#b77bfe"
brown = "#8a4f81"

bright_red = "#ffa1db"
bright_yellow = "#fbdcff"
bright_green = "#dbe4fe"
bright_cyan = "#a4f9ff"
bright_blue = "#94cafd"
bright_magenta = "#d2b3fd"
