mode = "light"

accent = "#a4018a"
selection = "#e7bee1"
muted = "#717585"

background = "#fdfdfe"
dark_background = "#f0f1f8"
darker_background = "#e3e4eb"
lighter_background = "#e9ebf3"

foreground = "#060815"
dark_foreground = "#525561"
light_foreground = "#2b2d38"
bright_foreground = "#010203"

hyprland_active_border = "rgba(066166ee) rgba(a4018aee) 45deg"
hyprland_inactive_border = "rgba(717585aa)"

red = "#b0062b"
yellow = "#615801"
orange = "#824900"
green = "#036532"
cyan = "#066166"
blue = "#0055b3"
magenta = "#a4018a"
brown = "#4e2c00"

bright_red = "#930021"
bright_yellow = "#504900"
bright_green = "#055329"
bright_cyan = "#095054"
bright_blue = "#004594"
bright_magenta = "#880072"
