mode = "light"

accent = "#ae1801"
selection = "#eac4be"
muted = "#69777e"

background = "#fefdfd"
dark_background = "#eef3f5"
darker_background = "#e1e5e8"
lighter_background = "#e6ecef"

foreground = "#020b10"
dark_foreground = "#4a585e"
light_foreground = "#243036"
bright_foreground = "#010203"

hyprland_active_border = "rgba(066264ee) rgba(ae1801ee) 45deg"
hyprland_inactive_border = "rgba(69777eaa)"

red = "#904005"
yellow = "#7c4e00"
orange = "#854906"
green = "#066263"
cyan = "#066264"
blue = "#015e79"
magenta = "#ae1801"
brown = "#502c04"

bright_red = "#783302"
bright_yellow = "#654004"
bright_green = "#045050"
bright_cyan = "#044f51"
bright_blue = "#004e65"
bright_magenta = "#920e00"
