mode = "dark"

accent = "#e856fe"
selection = "#582165"
muted = "#6b81a5"

background = "#000108"
dark_background = "#000106"
darker_background = "#000003"
lighter_background = "#08152c"

foreground = "#f2f5fb"
dark_foreground = "#a8aeb8"
light_foreground = "#d9dee6"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(22e7e2ee) rgba(e856feee) 45deg"
hyprland_inactive_border = "rgba(6b81a5aa)"

red = "#ac82ff"
yellow = "#aae0ff"
orange = "#9abaff"
green = "#1bdbf9"
cyan = "#22e7e2"
blue = "#699bfe"
magenta = "#e856fe"
brown = "#55668c"

bright_red = "#cab7fe"
bright_yellow = "#cfedff"
bright_green = "#b3f1fe"
bright_cyan = "#8cfffa"
bright_blue = "#a7c5fc"
bright_magenta = "#f1a2fd"
