mode = "dark"

accent = "#e550fe"
selection = "#45184c"
muted = "#516c4b"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#011000"

foreground = "#e4eae2"
dark_foreground = "#8d918c"
light_foreground = "#c6cdc4"
bright_foreground = "#f8fbf8"

hyprland_active_border = "rgba(15f441ee) rgba(e550feee) 45deg"
hyprland_inactive_border = "rgba(516c4baa)"

red = "#69a701"
yellow = "#eef300"
orange = "#abcd14"
green = "#d0b4fe"
cyan = "#15f441"
blue = "#0aa14e"
magenta = "#e550fe"
brown = "#56670a"

bright_red = "#8ac645"
bright_yellow = "#faffbb"
bright_green = "#e9dffc"
bright_cyan = "#bfffbf"
bright_blue = "#3ac26a"
bright_magenta = "#ee97fe"
