mode = "dark"

accent = "#fe49c2"
selection = "#4c163a"
muted = "#725c62"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#12080b"

foreground = "#efe5e7"
dark_foreground = "#948e8f"
light_foreground = "#d3c7ca"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(1ce5f2ee) rgba(fe49c2ee) 45deg"
hyprland_inactive_border = "rgba(725c62aa)"

red = "#fe423b"
yellow = "#ffe887"
orange = "#ffa44c"
green = "#acd809"
cyan = "#1ce5f2"
blue = "#497cfd"
magenta = "#fe49c2"
brown = "#805226"

bright_red = "#fe8b7e"
bright_yellow = "#fef9e2"
bright_green = "#cdf855"
bright_cyan = "#b7f9ff"
bright_blue = "#79a1fd"
bright_magenta = "#ff96d4"
