mode = "dark"

accent = "#fe6651"
selection = "#4c1f18"
muted = "#4d6d4e"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#001001"

foreground = "#e3eae3"
dark_foreground = "#8d918d"
light_foreground = "#c5cdc5"
bright_foreground = "#f8fbf8"

hyprland_active_border = "rgba(15f79cee) rgba(fe6651ee) 45deg"
hyprland_inactive_border = "rgba(4d6d4eaa)"

red = "#8b6d08"
yellow = "#f5ec11"
orange = "#c2a916"
green = "#6dd528"
cyan = "#15f79c"
blue = "#119d7b"
magenta = "#fe6651"
brown = "#61550b"

bright_red = "#ad8b20"
bright_yellow = "#fffdb7"
bright_green = "#b2eb99"
bright_cyan = "#d2fee3"
bright_blue = "#3ebd98"
bright_magenta = "#fea292"
