mode = "dark"

accent = "#fe53c7"
selection = "#61214c"
muted = "#6d8967"

background = "#000300"
dark_background = "#000200"
darker_background = "#000100"
lighter_background = "#081b05"

foreground = "#f2f6f1"
dark_foreground = "#a9b0a7"
light_foreground = "#dae0d9"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(04e8dfee) rgba(fe53c7ee) 45deg"
hyprland_inactive_border = "rgba(6d8967aa)"

red = "#ff645c"
yellow = "#eddc07"
orange = "#ffa338"
green = "#3fe94d"
cyan = "#04e8df"
blue = "#6a9bfe"
magenta = "#fe53c7"
brown = "#8c5a1f"

bright_red = "#fdaca3"
bright_yellow = "#feed1e"
bright_green = "#a3ffa2"
bright_cyan = "#91fef6"
bright_blue = "#a7c4fd"
bright_magenta = "#fda2da"
