mode = "dark"

accent = "#f945d9"
selection = "#4b1541"
muted = "#785480"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#140418"

foreground = "#ece5ed"
dark_foreground = "#928e93"
light_foreground = "#cfc8d1"
bright_foreground = "#fcf9fc"

hyprland_active_border = "rgba(10e8dbee) rgba(f945d9ee) 45deg"
hyprland_inactive_border = "rgba(785480aa)"

red = "#ff3574"
yellow = "#fee1d0"
orange = "#fe9f8e"
green = "#d1b4fd"
cyan = "#10e8db"
blue = "#6075ff"
magenta = "#f945d9"
brown = "#7f5047"

bright_red = "#fe879e"
bright_yellow = "#fff7f2"
bright_green = "#eadefe"
bright_cyan = "#a6fef5"
bright_blue = "#879dfc"
bright_magenta = "#ff91e6"
