mode = "dark"

accent = "#fe5e86"
selection = "#4c1c28"
muted = "#815849"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#1b0300"

foreground = "#efe5e2"
dark_foreground = "#948e8c"
light_foreground = "#d4c7c3"
bright_foreground = "#fdf9f8"

hyprland_active_border = "rgba(fec678ee) rgba(fe5e86ee) 45deg"
hyprland_inactive_border = "rgba(815849aa)"

red = "#d40924"
yellow = "#ffe714"
orange = "#f08e0c"
green = "#dab300"
cyan = "#fec678"
blue = "#cb6605"
magenta = "#fe5e86"
brown = "#784706"

bright_red = "#d76963"
bright_yellow = "#fffad5"
bright_green = "#f7d561"
bright_cyan = "#fef0dd"
bright_blue = "#e78a49"
bright_magenta = "#fd9eaf"
