mode = "dark"

accent = "#ff45de"
selection = "#651a54"
muted = "#a1736b"

background = "#060000"
dark_background = "#040000"
darker_background = "#020000"
lighter_background = "#290c08"

foreground = "#faf3f2"
dark_foreground = "#b7aba8"
light_foreground = "#e6dbd9"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(fec92fee) rgba(ff45deee) 45deg"
hyprland_inactive_border = "rgba(a1736baa)"

red = "#ff6365"
yellow = "#f0da1c"
orange = "#fea247"
green = "#fd9b5f"
cyan = "#fec92f"
blue = "#e78004"
magenta = "#ff45de"
brown = "#8c5927"

bright_red = "#feaba7"
bright_yellow = "#ffeb50"
bright_green = "#fecbaf"
bright_cyan = "#fee6ab"
bright_blue = "#fdb173"
bright_magenta = "#fe9fe7"
