mode = "light"

accent = "#9200b8"
selection = "#e2bfeb"
muted = "#777386"

background = "#fdfefc"
dark_background = "#f2f0f9"
darker_background = "#e5e3ec"
lighter_background = "#ece9f8"

foreground = "#0b0618"
dark_foreground = "#565360"
light_foreground = "#2e2c37"
bright_foreground = "#020103"

hyprland_active_border = "rgba(08616aee) rgba(9200b8ee) 45deg"
hyprland_inactive_border = "rgba(777386aa)"

red = "#ac045d"
yellow = "#7e4c07"
orange = "#9e311e"
green = "#9c04a1"
cyan = "#08616a"
blue = "#552ee4"
magenta = "#9200b8"
brown = "#5f1d12"

bright_red = "#90004c"
bright_yellow = "#683e04"
bright_green = "#810085"
bright_cyan = "#015058"
bright_blue = "#4900d5"
bright_magenta = "#7a009b"
