mode = "light"

accent = "#8d19ae"
selection = "#e1c4e9"
muted = "#7a7274"

background = "#fdfdfd"
dark_background = "#f2f2f2"
darker_background = "#e4e4e4"
lighter_background = "#ebebeb"

foreground = "#0d0809"
dark_foreground = "#5f5155"
light_foreground = "#372a2d"
bright_foreground = "#030102"

hyprland_active_border = "rgba(0d625cee) rgba(8d19aeee) 45deg"
hyprland_inactive_border = "rgba(7a7274aa)"

red = "#b30029"
yellow = "#685507"
orange = "#874600"
green = "#1a6600"
cyan = "#0d625c"
blue = "#055d7e"
magenta = "#8d19ae"
brown = "#512a00"

bright_red = "#920521"
bright_yellow = "#574602"
bright_green = "#135200"
bright_cyan = "#06504b"
bright_blue = "#004d6a"
bright_magenta = "#780296"
