mode = "dark"

accent = "#37bd1d"
selection = "#16490c"
muted = "#728772"

background = "#010201"
dark_background = "#010101"
darker_background = "#000100"
lighter_background = "#0d1a0d"

foreground = "#f2f7f2"
dark_foreground = "#a8b1a8"
light_foreground = "#d9e0d9"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(4ff675ee) rgba(37bd1dee) 45deg"
hyprland_inactive_border = "rgba(728772aa)"

red = "#36bd1e"
yellow = "#73fa6a"
orange = "#56db48"
green = "#11db5f"
cyan = "#4ff675"
blue = "#0dbe48"
magenta = "#37bd1d"
brown = "#2f7828"

bright_red = "#7ee06f"
bright_yellow = "#b4ffad"
bright_green = "#7af794"
bright_cyan = "#b0feb9"
bright_blue = "#6ae27d"
bright_magenta = "#7ee06f"
