mode = "dark"

accent = "#ea53ed"
selection = "#461947"
muted = "#675d7c"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#0e0719"

foreground = "#e9e6ef"
dark_foreground = "#908f94"
light_foreground = "#ccc8d3"
bright_foreground = "#faf9fd"

hyprland_active_border = "rgba(1ce5f3ee) rgba(ea53edee) 45deg"
hyprland_inactive_border = "rgba(675d7caa)"

red = "#fe396b"
yellow = "#fee4bc"
orange = "#fea277"
green = "#17ea6d"
cyan = "#1ce5f3"
blue = "#776cff"
magenta = "#ea53ed"
brown = "#7f513c"

bright_red = "#fe8898"
bright_yellow = "#fef8ef"
bright_green = "#9fffb2"
bright_cyan = "#b9f8fe"
bright_blue = "#9697fe"
bright_magenta = "#f495f4"
