mode = "dark"

accent = "#ec55ee"
selection = "#5b215e"
muted = "#857a9a"

background = "#020105"
dark_background = "#010104"
darker_background = "#010002"
lighter_background = "#191125"

foreground = "#f6f4fa"
dark_foreground = "#afacb6"
light_foreground = "#dfdce5"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1ce5f3ee) rgba(ec55eeee) 45deg"
hyprland_inactive_border = "rgba(857a9aaa)"

red = "#ff5f7d"
yellow = "#fecf86"
orange = "#fda075"
green = "#17ea6d"
cyan = "#1ce5f3"
blue = "#8f8ffe"
magenta = "#ec55ee"
brown = "#8b5840"

bright_red = "#fea9b2"
bright_yellow = "#fee4bc"
bright_green = "#9effb2"
bright_cyan = "#abf7fe"
bright_blue = "#babefe"
bright_magenta = "#ff98fe"
