mode = "light"

accent = "#9c03a0"
selection = "#e5bfe7"
muted = "#787383"

background = "#fdfdfe"
dark_background = "#f2f0f7"
darker_background = "#e5e3ea"
lighter_background = "#ece9f2"

foreground = "#0b0713"
dark_foreground = "#57535f"
light_foreground = "#2f2c37"
bright_foreground = "#020103"

hyprland_active_border = "rgba(066168ee) rgba(9c03a0ee) 45deg"
hyprland_inactive_border = "rgba(787383aa)"

red = "#ae043f"
yellow = "#755002"
orange = "#943c03"
green = "#00662a"
cyan = "#066168"
blue = "#552ee4"
magenta = "#9c03a0"
brown = "#592402"

bright_red = "#920133"
bright_yellow = "#614203"
bright_green = "#025422"
bright_cyan = "#004f55"
bright_blue = "#4a00d5"
bright_magenta = "#810084"
