mode = "dark"

accent = "#cbaef3"
selection = "#403e54"
muted = "#4d6871"

background = "#0a1316"
dark_background = "#080e11"
darker_background = "#050a0b"
lighter_background = "#172124"

foreground = "#e0eaed"
dark_foreground = "#959fa2"
light_foreground = "#c0cdd1"
bright_foreground = "#f7fbfc"

hyprland_active_border = "rgba(79e5e9ee) rgba(cbaef3ee) 45deg"
hyprland_inactive_border = "rgba(4d6871aa)"

red = "#f09da2"
yellow = "#f4dd90"
orange = "#feb98c"
green = "#7ce0ca"
cyan = "#79e5e9"
blue = "#6cbce7"
magenta = "#cbaef3"
brown = "#7f5d46"

bright_red = "#fbc9cb"
bright_yellow = "#fef9e4"
bright_green = "#c3f8eb"
bright_cyan = "#cafdfe"
bright_blue = "#add8f1"
bright_magenta = "#e6d5fe"
