mode = "light"

accent = "#674b88"
selection = "#d6d1e1"
muted = "#6a777c"

background = "#fbfeff"
dark_background = "#eff2f4"
darker_background = "#e1e5e7"
lighter_background = "#e7ecee"

foreground = "#020b0e"
dark_foreground = "#49585d"
light_foreground = "#233035"
bright_foreground = "#000203"

hyprland_active_border = "rgba(066264ee) rgba(674b88ee) 45deg"
hyprland_inactive_border = "rgba(6a777caa)"

red = "#8a4147"
yellow = "#6a5600"
orange = "#82491c"
green = "#0a6355"
cyan = "#066264"
blue = "#015e83"
magenta = "#674b88"
brown = "#4e2c11"

bright_red = "#7a2f38"
bright_yellow = "#564604"
bright_green = "#055145"
bright_cyan = "#044f51"
bright_blue = "#064d6b"
bright_magenta = "#573a78"
