mode = "dark"

accent = "#ec9dee"
selection = "#51345d"
muted = "#695a85"

background = "#150b24"
dark_background = "#10081b"
darker_background = "#0b0612"
lighter_background = "#231933"

foreground = "#e9e6ef"
dark_foreground = "#9f99a8"
light_foreground = "#ccc8d3"
bright_foreground = "#faf9fd"

hyprland_active_border = "rgba(2debf9ee) rgba(ec9deeee) 45deg"
hyprland_inactive_border = "rgba(695a85aa)"

red = "#fb90bf"
yellow = "#fedc67"
orange = "#fdb89c"
green = "#44e8c8"
cyan = "#2debf9"
blue = "#aea3ff"
magenta = "#ec9dee"
brown = "#7f5c4e"

bright_red = "#fec5dc"
bright_yellow = "#fef8e6"
bright_green = "#acffea"
bright_cyan = "#d3fafe"
bright_blue = "#cecafd"
bright_magenta = "#fecafe"
