mode = "dark"

accent = "#8593fd"
selection = "#333965"
muted = "#6284a2"

background = "#000208"
dark_background = "#000106"
darker_background = "#000103"
lighter_background = "#00182b"

foreground = "#f1f6fa"
dark_foreground = "#a6afb7"
light_foreground = "#d8dfe6"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(17eeecee) rgba(8593fdee) 45deg"
hyprland_inactive_border = "rgba(6284a2aa)"

red = "#02b5b2"
yellow = "#82e9fe"
orange = "#52cfd9"
green = "#05d6ad"
cyan = "#17eeec"
blue = "#49a2fe"
magenta = "#8593fd"
brown = "#2d7277"

bright_red = "#1fe0db"
bright_yellow = "#bcf3fe"
bright_green = "#5cf6ce"
bright_cyan = "#89fffc"
bright_blue = "#98c8ff"
bright_magenta = "#b4c0fd"
