mode = "dark"

accent = "#8593fd"
selection = "#282c4c"
muted = "#456783"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#000c1e"

foreground = "#e2e9f0"
dark_foreground = "#8c9095"
light_foreground = "#c3ccd4"
bright_foreground = "#f7fafd"

hyprland_active_border = "rgba(17eeecee) rgba(8593fdee) 45deg"
hyprland_inactive_border = "rgba(456783aa)"

red = "#008380"
yellow = "#b2f1fe"
orange = "#67b9bf"
green = "#05d6ad"
cyan = "#17eeec"
blue = "#2288e8"
magenta = "#8593fd"
brown = "#345d60"

bright_red = "#1aa3a0"
bright_yellow = "#f0fbfd"
bright_green = "#5cf6ce"
bright_cyan = "#c6fffd"
bright_blue = "#5da8fa"
bright_magenta = "#acb9fc"
