mode = "light"

accent = "#454ab7"
selection = "#d0d0eb"
muted = "#667785"

background = "#fefdfc"
dark_background = "#ebf3fa"
darker_background = "#dee6ec"
lighter_background = "#e3edf5"

foreground = "#000a16"
dark_foreground = "#4c5760"
light_foreground = "#262f37"
bright_foreground = "#010203"

hyprland_active_border = "rgba(076261ee) rgba(454ab7ee) 45deg"
hyprland_inactive_border = "rgba(667785aa)"

red = "#086260"
yellow = "#0c606d"
orange = "#066167"
green = "#066450"
cyan = "#076261"
blue = "#0559a0"
magenta = "#454ab7"
brown = "#043a3e"

bright_red = "#09504e"
bright_yellow = "#004e5a"
bright_green = "#045141"
bright_cyan = "#094f4f"
bright_blue = "#024885"
bright_magenta = "#3836a9"
