mode = "dark"

accent = "#b77bfe"
selection = "#463162"
muted = "#538c8b"

background = "#000303"
dark_background = "#000202"
darker_background = "#000101"
lighter_background = "#001b1b"

foreground = "#eff7f7"
dark_foreground = "#a4b1b1"
light_foreground = "#d5e1e0"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1be9d7ee) rgba(b77bfeee) 45deg"
hyprland_inactive_border = "rgba(538c8baa)"

red = "#12be53"
yellow = "#c6ea00"
orange = "#7fd53b"
green = "#15e6a8"
cyan = "#1be9d7"
blue = "#19b1cd"
magenta = "#b77bfe"
brown = "#467520"

bright_red = "#55e57a"
bright_yellow = "#d7fa51"
bright_green = "#90ffd0"
bright_cyan = "#93fff1"
bright_blue = "#1adafd"
bright_magenta = "#d2b3fe"
