mode = "dark"

accent = "#e25bf1"
selection = "#441b48"
muted = "#6e5f63"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#0f090b"

foreground = "#efe5e7"
dark_foreground = "#948e8f"
light_foreground = "#d3c7ca"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(15e8d9ee) rgba(e25bf1ee) 45deg"
hyprland_inactive_border = "rgba(6e5f63aa)"

red = "#fe4143"
yellow = "#feec24"
orange = "#fea542"
green = "#a1db00"
cyan = "#15e8d9"
blue = "#2780fe"
magenta = "#e25bf1"
brown = "#7f5321"

bright_red = "#fd8c83"
bright_yellow = "#fffbce"
bright_green = "#c4fa61"
bright_cyan = "#a4fff4"
bright_blue = "#6aa5fd"
bright_magenta = "#f492fe"
