mode = "dark"

accent = "#ff93e1"
selection = "#643857"
muted = "#9c7285"

background = "#050002"
dark_background = "#040001"
darker_background = "#020001"
lighter_background = "#260b19"

foreground = "#faf3f6"
dark_foreground = "#b6aaaf"
light_foreground = "#e5dbdf"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(16eeedee) rgba(ff93e1ee) 45deg"
hyprland_inactive_border = "rgba(9c7285aa)"

red = "#fd93a9"
yellow = "#ffd343"
orange = "#fdb48d"
green = "#37ef8a"
cyan = "#16eeed"
blue = "#99abfd"
magenta = "#ff93e1"
brown = "#8b634e"

bright_red = "#fec6d0"
bright_yellow = "#fee6a2"
bright_green = "#aaffc4"
bright_cyan = "#8cfefd"
bright_blue = "#c3cffd"
bright_magenta = "#fecdee"
