mode = "light"

accent = "#9f1585"
selection = "#e7c3e0"
muted = "#846f78"

background = "#fffdfe"
dark_background = "#f9eff3"
darker_background = "#ebe1e6"
lighter_background = "#f4e7ed"

foreground = "#13040b"
dark_foreground = "#5e5157"
light_foreground = "#362a2f"
bright_foreground = "#030102"

hyprland_active_border = "rgba(076262ee) rgba(9f1585ee) 45deg"
hyprland_inactive_border = "rgba(846f78aa)"

red = "#b0004c"
yellow = "#6c5500"
orange = "#8f4003"
green = "#096535"
cyan = "#076262"
blue = "#3f46ca"
magenta = "#9f1585"
brown = "#562602"

bright_red = "#91003d"
bright_yellow = "#584503"
bright_green = "#00542a"
bright_cyan = "#05504f"
bright_blue = "#3230bc"
bright_magenta = "#870270"
