mode = "light"

accent = "#9d0197"
selection = "#e6bee3"
muted = "#6c7587"

background = "#fefdfc"
dark_background = "#eef2fa"
darker_background = "#e1e5ed"
lighter_background = "#e6ebf6"

foreground = "#040817"
dark_foreground = "#505561"
light_foreground = "#292e38"
bright_foreground = "#010203"

hyprland_active_border = "rgba(066264ee) rgba(9d0197ee) 45deg"
hyprland_inactive_border = "rgba(6c7587aa)"

red = "#b3002a"
yellow = "#645700"
orange = "#844800"
green = "#026617"
cyan = "#066264"
blue = "#0050c1"
magenta = "#9d0197"
brown = "#4f2b00"

bright_red = "#940020"
bright_yellow = "#514603"
bright_green = "#035312"
bright_cyan = "#044f52"
bright_blue = "#0042a1"
bright_magenta = "#83007f"
