mode = "dark"

accent = "#fe54b7"
selection = "#612248"
muted = "#528b8e"

background = "#000304"
dark_background = "#000203"
darker_background = "#000102"
lighter_background = "#001b1c"

foreground = "#eff7f7"
dark_foreground = "#a4b1b2"
light_foreground = "#d5e1e1"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1ee9d6ee) rgba(fe54b7ee) 45deg"
hyprland_inactive_border = "rgba(528b8eaa)"

red = "#ff6365"
yellow = "#fecf86"
orange = "#fea069"
green = "#01e5b0"
cyan = "#1ee9d6"
blue = "#0fb1c9"
magenta = "#fe54b7"
brown = "#8c583a"

bright_red = "#fdaba7"
bright_yellow = "#fee4be"
bright_green = "#8bffd6"
bright_cyan = "#93fff0"
bright_blue = "#0adcf9"
bright_magenta = "#ffa3d1"
