mode = "dark"

accent = "#e1a4ed"
selection = "#443147"
muted = "#685c81"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#0f051d"

foreground = "#e9e6ef"
dark_foreground = "#908f94"
light_foreground = "#ccc8d3"
bright_foreground = "#faf9fd"

hyprland_active_border = "rgba(61e6ffee) rgba(e1a4edee) 45deg"
hyprland_inactive_border = "rgba(685c81aa)"

red = "#f097c5"
yellow = "#f9dd7d"
orange = "#feb79e"
green = "#58e3dc"
cyan = "#61e6ff"
blue = "#8eaffe"
magenta = "#e1a4ed"
brown = "#7f5c4f"

bright_red = "#ffc3e1"
bright_yellow = "#fef9e4"
bright_green = "#a4fef8"
bright_cyan = "#daf8ff"
bright_blue = "#bdd1fe"
bright_magenta = "#f6cefd"
