mode = "dark"

accent = "#ff44ca"
selection = "#4d143d"
muted = "#4c6585"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#000b1f"

foreground = "#e3e8f0"
dark_foreground = "#8d9095"
light_foreground = "#c4cbd4"
bright_foreground = "#f8fafd"

hyprland_active_border = "rgba(1fe4f6ee) rgba(ff44caee) 45deg"
hyprland_inactive_border = "rgba(4c6585aa)"

red = "#ff3965"
yellow = "#feed0d"
orange = "#ffa455"
green = "#b1d60f"
cyan = "#1fe4f6"
blue = "#118ed5"
magenta = "#ff44ca"
brown = "#80522b"

bright_red = "#fe8895"
bright_yellow = "#fffbca"
bright_green = "#d4f56b"
bright_cyan = "#bef7fe"
bright_blue = "#2eaeff"
bright_magenta = "#fe95d9"
