mode = "light"

accent = "#6738c1"
selection = "#d8ccef"
muted = "#6a7683"

background = "#fdfdfe"
dark_background = "#edf2f8"
darker_background = "#e0e5ea"
lighter_background = "#e5ecf3"

foreground = "#020a14"
dark_foreground = "#4d5660"
light_foreground = "#262f38"
bright_foreground = "#010203"

hyprland_active_border = "rgba(066263ee) rgba(6738c1ee) 45deg"
hyprland_inactive_border = "rgba(6a7683aa)"

red = "#ae043d"
yellow = "#665600"
orange = "#8a4400"
green = "#06643f"
cyan = "#066263"
blue = "#045b92"
magenta = "#6738c1"
brown = "#532900"

bright_red = "#910532"
bright_yellow = "#544704"
bright_green = "#005333"
bright_cyan = "#045051"
bright_blue = "#054b7a"
bright_magenta = "#5a1eb3"
