mode = "dark"

accent = "#a486fd"
selection = "#31284c"
muted = "#4d667f"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#010c1b"

foreground = "#e2e9f0"
dark_foreground = "#8c9095"
light_foreground = "#c3cbd4"
bright_foreground = "#f8fafd"

hyprland_active_border = "rgba(1ce6e9ee) rgba(a486fdee) 45deg"
hyprland_inactive_border = "rgba(4d667faa)"

red = "#f34e6e"
yellow = "#ffe887"
orange = "#ffa362"
green = "#17e798"
cyan = "#1ce6e9"
blue = "#108cdd"
magenta = "#a486fd"
brown = "#805231"

bright_red = "#fe8897"
bright_yellow = "#fff9e1"
bright_green = "#94ffc6"
bright_cyan = "#a2feff"
bright_blue = "#43acfd"
bright_magenta = "#c0b1fd"
