mode = "dark"

accent = "#cdacf8"
selection = "#4f4262"
muted = "#7a7d9e"

background = "#010106"
dark_background = "#010104"
darker_background = "#000002"
lighter_background = "#131428"

foreground = "#f4f5fb"
dark_foreground = "#acadb8"
light_foreground = "#dcdde6"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(6ce7efee) rgba(cdacf8ee) 45deg"
hyprland_inactive_border = "rgba(7a7d9eaa)"

red = "#e59cd1"
yellow = "#f5d480"
orange = "#ffb1a0"
green = "#81e1b7"
cyan = "#6ce7ef"
blue = "#99acf7"
magenta = "#cdacf8"
brown = "#8c6158"

bright_red = "#fec2ed"
bright_yellow = "#fee6a8"
bright_green = "#b0fbd8"
bright_cyan = "#a8f8fe"
bright_blue = "#c2cfff"
bright_magenta = "#e6d5fe"
