mode = "dark"

accent = "#ac82ff"
selection = "#34274d"
muted = "#625c89"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#0c061e"

foreground = "#e7e7f0"
dark_foreground = "#8f8f95"
light_foreground = "#cac9d4"
bright_foreground = "#fafafd"

hyprland_active_border = "rgba(0beea9ee) rgba(ac82ffee) 45deg"
hyprland_inactive_border = "rgba(625c89aa)"

red = "#f403d1"
yellow = "#e9f516"
orange = "#fda278"
green = "#82e214"
cyan = "#0beea9"
blue = "#6d71fe"
magenta = "#ac82ff"
brown = "#7f513c"

bright_red = "#fe77df"
bright_yellow = "#f8ffc3"
bright_green = "#b0ff76"
bright_cyan = "#b5fedb"
bright_blue = "#8f9aff"
bright_magenta = "#c5aefd"
