mode = "light"

accent = "#7908e1"
selection = "#dcc0f5"
muted = "#757387"

background = "#fdfdfc"
dark_background = "#f1f1fa"
darker_background = "#e4e3ec"
lighter_background = "#eae9f8"

foreground = "#090618"
dark_foreground = "#555460"
light_foreground = "#2d2c37"
bright_foreground = "#020103"

hyprland_active_border = "rgba(036445ee) rgba(7908e1ee) 45deg"
hyprland_inactive_border = "rgba(757387aa)"

red = "#a2008a"
yellow = "#575c04"
orange = "#943c04"
green = "#356203"
cyan = "#036445"
blue = "#4d18fe"
magenta = "#7908e1"
brown = "#592402"

bright_red = "#870372"
bright_yellow = "#474b00"
bright_green = "#2b5102"
bright_cyan = "#065137"
bright_blue = "#4000db"
bright_magenta = "#6400bc"
