mode = "light"

accent = "#7b2eb3"
selection = "#ddc9ea"
muted = "#757387"

background = "#fdfdfc"
dark_background = "#f1f1fa"
darker_background = "#e4e3ec"
lighter_background = "#eae9f8"

foreground = "#090618"
dark_foreground = "#555460"
light_foreground = "#2d2c37"
bright_foreground = "#020103"

hyprland_active_border = "rgba(ac1d02ee) rgba(7b2eb3ee) 45deg"
hyprland_inactive_border = "rgba(757387aa)"

red = "#ae043b"
yellow = "#824906"
orange = "#9c330c"
green = "#a11281"
cyan = "#ac1d02"
blue = "#4a42c8"
magenta = "#7b2eb3"
brown = "#5e1f07"

bright_red = "#910530"
bright_yellow = "#6d3b00"
bright_green = "#89006d"
bright_cyan = "#901400"
bright_blue = "#3e2bbb"
bright_magenta = "#6d0da5"
