mode = "light"

accent = "#28559f"
selection = "#c8d3e6"
muted = "#667881"

background = "#fdfdfe"
dark_background = "#ecf3f7"
darker_background = "#dfe6e9"
lighter_background = "#e3edf2"

foreground = "#000b12"
dark_foreground = "#4a585e"
light_foreground = "#243036"
bright_foreground = "#010203"

hyprland_active_border = "rgba(0c625cee) rgba(28559fee) 45deg"
hyprland_inactive_border = "rgba(667881aa)"

red = "#08616b"
yellow = "#0c606e"
orange = "#0a616d"
green = "#076261"
cyan = "#0c625c"
blue = "#075d88"
magenta = "#28559f"
brown = "#063a41"

bright_red = "#014f57"
bright_yellow = "#074f5b"
bright_green = "#01504f"
bright_cyan = "#04504b"
bright_blue = "#064c6f"
bright_magenta = "#144591"
