mode = "dark"

accent = "#b27efe"
selection = "#453165"
muted = "#85789f"

background = "#020107"
dark_background = "#010105"
darker_background = "#010003"
lighter_background = "#1a1029"

foreground = "#f6f4fa"
dark_foreground = "#afacb6"
light_foreground = "#dfdce5"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(c9ccffee) rgba(b27efeee) 45deg"
hyprland_inactive_border = "rgba(85789faa)"

red = "#ea60db"
yellow = "#ebc8fd"
orange = "#e999f3"
green = "#b4abfd"
cyan = "#c9ccff"
blue = "#7997fe"
magenta = "#b27efe"
brown = "#805486"

bright_red = "#fe9cf1"
bright_yellow = "#f3dffe"
bright_green = "#d5d2fe"
bright_cyan = "#e4e6fd"
bright_blue = "#aec2fd"
bright_magenta = "#cfb5ff"
