mode = "light"

accent = "#9f2c3d"
selection = "#e7c9cb"
muted = "#7b7368"

background = "#fffdfa"
dark_background = "#f4f1ed"
darker_background = "#e7e4e0"
lighter_background = "#eeebe5"

foreground = "#0e0802"
dark_foreground = "#5b5449"
light_foreground = "#332d23"
bright_foreground = "#020201"

hyprland_active_border = "rgba(036349ee) rgba(9f2c3dee) 45deg"
hyprland_inactive_border = "rgba(7b7368aa)"

red = "#9f3213"
yellow = "#6f5400"
orange = "#824900"
green = "#5b5b00"
cyan = "#036349"
blue = "#0c5f7c"
magenta = "#9f2c3d"
brown = "#4e2c00"

bright_red = "#882201"
bright_yellow = "#5b4400"
bright_green = "#4a4a00"
bright_cyan = "#05523c"
bright_blue = "#004e67"
bright_magenta = "#8f102c"
