mode = "dark"

accent = "#fe838c"
selection = "#623235"
muted = "#8d7e65"

background = "#030100"
dark_background = "#020100"
darker_background = "#010000"
lighter_background = "#1d1406"

foreground = "#f8f5ef"
dark_foreground = "#b3ada4"
light_foreground = "#e2ddd5"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(39dcaaee) rgba(fe838cee) 45deg"
hyprland_inactive_border = "rgba(8d7e65aa)"

red = "#f37e60"
yellow = "#fcca4b"
orange = "#ffa249"
green = "#c5c541"
cyan = "#39dcaa"
blue = "#04b4e9"
magenta = "#fe838c"
brown = "#8c5928"

bright_red = "#fead97"
bright_yellow = "#fee5ae"
bright_green = "#e4e57f"
bright_cyan = "#82f9cd"
bright_blue = "#69d3ff"
bright_magenta = "#feb9bb"
