mode = "dark"

accent = "#12bb7c"
selection = "#07492f"
muted = "#6b8971"

background = "#000300"
dark_background = "#000200"
darker_background = "#000100"
lighter_background = "#071b0c"

foreground = "#f1f7f2"
dark_foreground = "#a8b1a9"
light_foreground = "#d9e0da"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(51f75bee) rgba(12bb7cee) 45deg"
hyprland_inactive_border = "rgba(6b8971aa)"

red = "#79b306"
yellow = "#cfe717"
orange = "#a3cd0c"
green = "#11dc4b"
cyan = "#51f75b"
blue = "#15bc6d"
magenta = "#12bb7c"
brown = "#5a7107"

bright_red = "#9cdb3f"
bright_yellow = "#dff848"
bright_green = "#77f886"
bright_cyan = "#b3feb1"
bright_blue = "#30e78a"
bright_magenta = "#18e79b"
