mode = "light"

accent = "#ab1541"
selection = "#eac3cd"
muted = "#7d746b"

background = "#fffdfb"
dark_background = "#f4f1ef"
darker_background = "#e6e4e1"
lighter_background = "#eeeae7"

foreground = "#0e0803"
dark_foreground = "#5d5449"
light_foreground = "#342c23"
bright_foreground = "#030101"

hyprland_active_border = "rgba(824906ee) rgba(ab1541ee) 45deg"
hyprland_inactive_border = "rgba(7d746baa)"

red = "#ac1b18"
yellow = "#774f06"
orange = "#8e4200"
green = "#6e5400"
cyan = "#824906"
blue = "#0a5f75"
magenta = "#ab1541"
brown = "#552800"

bright_red = "#940509"
bright_yellow = "#644103"
bright_green = "#5a4405"
bright_cyan = "#6c3b00"
bright_blue = "#004f63"
bright_magenta = "#920033"
