mode = "dark"

accent = "#ff20f1"
selection = "#490a45"
muted = "#6e5f63"

background = "#020202"
dark_background = "#020202"
darker_background = "#010101"
lighter_background = "#0b0b0b"

foreground = "#efe5e7"
dark_foreground = "#9c9697"
light_foreground = "#d3c7ca"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(1be6edee) rgba(ff20f1ee) 45deg"
hyprland_inactive_border = "rgba(6e5f63aa)"

red = "#fe423d"
yellow = "#f4f10c"
orange = "#fda635"
green = "#1dec0b"
cyan = "#1be6ed"
blue = "#2a80fe"
magenta = "#ff20f1"
brown = "#7f531b"

bright_red = "#fd8c80"
bright_yellow = "#feffa8"
bright_green = "#a7ff9e"
bright_cyan = "#abfcff"
bright_blue = "#6ba5fd"
bright_magenta = "#fe8ff1"
