mode = "light"

accent = "#a6007e"
selection = "#e8bfda"
muted = "#787564"

background = "#fefef9"
dark_background = "#f3f2eb"
darker_background = "#e6e5de"
lighter_background = "#edebe3"

foreground = "#0c0900"
dark_foreground = "#585649"
light_foreground = "#302e23"
bright_foreground = "#020201"

hyprland_active_border = "rgba(5d5a06ee) rgba(a6007eee) 45deg"
hyprland_inactive_border = "rgba(787564aa)"

red = "#b30614"
yellow = "#655600"
orange = "#834900"
green = "#3a6300"
cyan = "#5d5a06"
blue = "#085f80"
magenta = "#a6007e"
brown = "#4f2c00"

bright_red = "#95000c"
bright_yellow = "#544701"
bright_green = "#2e5002"
bright_cyan = "#4d4a00"
bright_blue = "#004d6b"
bright_magenta = "#8a0168"
