mode = "dark"

accent = "#d496c9"
selection = "#533a4c"
muted = "#937b69"

background = "#040100"
dark_background = "#030100"
darker_background = "#020000"
lighter_background = "#201308"

foreground = "#f9f4f0"
dark_foreground = "#b5aca5"
light_foreground = "#e4dcd6"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(65d2d4ee) rgba(d496c9ee) 45deg"
hyprland_inactive_border = "rgba(937b69aa)"

red = "#dc8c82"
yellow = "#f2cb83"
orange = "#eda97c"
green = "#9dce8f"
cyan = "#65d2d4"
blue = "#72aae1"
magenta = "#d496c9"
brown = "#825d44"

bright_red = "#f4b1a8"
bright_yellow = "#fee4b7"
bright_green = "#c4ebb8"
bright_cyan = "#9deff0"
bright_blue = "#9cc9f6"
bright_magenta = "#eebbe5"
