mode = "dark"

accent = "#f6668e"
selection = "#531e28"
muted = "#82574c"

background = "#140201"
dark_background = "#0f0201"
darker_background = "#0a0101"
lighter_background = "#230c07"

foreground = "#f0e5e2"
dark_foreground = "#a39693"
light_foreground = "#d4c7c4"
bright_foreground = "#fdf9f8"

hyprland_active_border = "rgba(fec29dee) rgba(f6668eee) 45deg"
hyprland_inactive_border = "rgba(82574caa)"

red = "#c5372e"
yellow = "#fedfb9"
orange = "#e69261"
green = "#fe996d"
cyan = "#fec29d"
blue = "#dd4c5d"
magenta = "#f6668e"
brown = "#734931"

bright_red = "#d66b5e"
bright_yellow = "#fef7f0"
bright_green = "#ffcab4"
bright_cyan = "#ffeee4"
bright_blue = "#ee7e85"
bright_magenta = "#fe9db3"
