mode = "dark"

accent = "#f1735a"
selection = "#47291b"
muted = "#576a4d"

background = "#050c02"
dark_background = "#040902"
darker_background = "#030601"
lighter_background = "#10190b"

foreground = "#e4eae2"
dark_foreground = "#969c94"
light_foreground = "#c6cdc3"
bright_foreground = "#f9fbf7"

hyprland_active_border = "rgba(86ed8fee) rgba(f1735aee) 45deg"
hyprland_inactive_border = "rgba(576a4daa)"

red = "#a45e05"
yellow = "#f1ec5f"
orange = "#d3a122"
green = "#91cc58"
cyan = "#86ed8f"
blue = "#009f6e"
magenta = "#f1735a"
brown = "#6a5111"

bright_red = "#b98250"
bright_yellow = "#fffeb3"
bright_green = "#c1e5a4"
bright_cyan = "#d7fed8"
bright_blue = "#69b793"
bright_magenta = "#f4a797"
