mode = "light"

accent = "#9c03a0"
selection = "#e6bfe7"
muted = "#7b7183"

background = "#fefdff"
dark_background = "#f4f0f8"
darker_background = "#e7e2eb"
lighter_background = "#efe8f5"

foreground = "#0e0515"
dark_foreground = "#59525e"
light_foreground = "#312b35"
bright_foreground = "#020103"

hyprland_active_border = "rgba(086260ee) rgba(9c03a0ee) 45deg"
hyprland_inactive_border = "rgba(7b7183aa)"

red = "#ab0066"
yellow = "#725200"
orange = "#9c330a"
green = "#006453"
cyan = "#086260"
blue = "#5c27ea"
magenta = "#9c03a0"
brown = "#5e1f06"

bright_red = "#8e0354"
bright_yellow = "#5e4200"
bright_green = "#005143"
bright_cyan = "#00504e"
bright_blue = "#4e01d1"
bright_magenta = "#810084"
