mode = "dark"

accent = "#d06fee"
selection = "#3e2147"
muted = "#685c81"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#0f051d"

foreground = "#e9e6ef"
dark_foreground = "#908f94"
light_foreground = "#ccc8d3"
bright_foreground = "#faf9fd"

hyprland_active_border = "rgba(20e7e4ee) rgba(d06feeee) 45deg"
hyprland_inactive_border = "rgba(685c81aa)"

red = "#f24e75"
yellow = "#fee3c4"
orange = "#fea17f"
green = "#8bdf47"
cyan = "#20e7e4"
blue = "#826bf6"
magenta = "#d06fee"
brown = "#7f5140"

bright_red = "#ff869b"
bright_yellow = "#fef7f0"
bright_green = "#bafb90"
bright_cyan = "#a3fefb"
bright_blue = "#9f94fe"
bright_magenta = "#e69dfd"
