mode = "dark"

accent = "#b77bfe"
selection = "#37254c"
muted = "#625c89"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#0c061e"

foreground = "#e7e7f0"
dark_foreground = "#8f8f95"
light_foreground = "#cac9d4"
bright_foreground = "#fafafd"

hyprland_active_border = "rgba(1be5f1ee) rgba(b77bfeee) 45deg"
hyprland_inactive_border = "rgba(625c89aa)"

red = "#ed3db9"
yellow = "#fadcfe"
orange = "#f397e6"
green = "#afc2fc"
cyan = "#1be5f1"
blue = "#0a8ae3"
magenta = "#b77bfe"
brown = "#7a4c73"

bright_red = "#ee8bc9"
bright_yellow = "#fcf6fd"
bright_green = "#dbe4fe"
bright_cyan = "#b6f9fe"
bright_blue = "#54abf8"
bright_magenta = "#ceaafe"
