mode = "dark"

accent = "#f942f2"
selection = "#61195f"
muted = "#917597"

background = "#040005"
dark_background = "#030004"
darker_background = "#020002"
lighter_background = "#200d24"

foreground = "#f8f3f8"
dark_foreground = "#b2abb4"
light_foreground = "#e2dce3"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1ce5f3ee) rgba(f942f2ee) 45deg"
hyprland_inactive_border = "rgba(917597aa)"

red = "#fd5e86"
yellow = "#ffd403"
orange = "#fea068"
green = "#0de79e"
cyan = "#1ce5f3"
blue = "#44a3fd"
magenta = "#f942f2"
brown = "#8c5839"

bright_red = "#ffa8b7"
bright_yellow = "#ffe796"
bright_green = "#94ffca"
bright_cyan = "#acf7fe"
bright_blue = "#98c9fc"
bright_magenta = "#fe9bf7"
