mode = "dark"

accent = "#fe664f"
selection = "#612821"
muted = "#688594"

background = "#000204"
dark_background = "#000103"
darker_background = "#000102"
lighter_background = "#061821"

foreground = "#f0f6f9"
dark_foreground = "#a5b0b6"
light_foreground = "#d6e0e4"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1ce6eaee) rgba(fe664fee) 45deg"
hyprland_inactive_border = "rgba(688594aa)"

red = "#f87100"
yellow = "#fdce96"
orange = "#fba356"
green = "#00e0e1"
cyan = "#1ce6ea"
blue = "#13aedb"
magenta = "#fe664f"
brown = "#8a5a2f"

bright_red = "#ffae84"
bright_yellow = "#fee3c4"
bright_green = "#74fefe"
bright_cyan = "#91fdff"
bright_blue = "#60d4ff"
bright_magenta = "#feac9c"
