mode = "dark"

accent = "#fe4cc9"
selection = "#641d4d"
muted = "#9c7574"

background = "#050001"
dark_background = "#040001"
darker_background = "#020000"
lighter_background = "#250e0e"

foreground = "#faf3f3"
dark_foreground = "#b7aaaa"
light_foreground = "#e6dbdb"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1de6e8ee) rgba(fe4cc9ee) 45deg"
hyprland_inactive_border = "rgba(9c7574aa)"

red = "#ff645b"
yellow = "#fed343"
orange = "#fea251"
green = "#13ea73"
cyan = "#1de6e8"
blue = "#3fa4fc"
magenta = "#fe4cc9"
brown = "#8c592d"

bright_red = "#ffaba2"
bright_yellow = "#fee6a2"
bright_green = "#9ffeb5"
bright_cyan = "#8bfeff"
bright_blue = "#96c9fc"
bright_magenta = "#fea1db"
