mode = "light"

accent = "#9800ad"
selection = "#e2bfe7"
muted = "#6b7968"

background = "#fbfffa"
dark_background = "#eef4ec"
darker_background = "#e0e7df"
lighter_background = "#e6eee4"

foreground = "#030c02"
dark_foreground = "#50584e"
light_foreground = "#293027"
bright_foreground = "#010201"

hyprland_active_border = "rgba(046616ee) rgba(9800adee) 45deg"
hyprland_inactive_border = "rgba(6b7968aa)"

red = "#3d6205"
yellow = "#595b01"
orange = "#4d5e00"
green = "#8005d9"
cyan = "#046616"
blue = "#00662e"
magenta = "#9800ad"
brown = "#2e3800"

bright_red = "#315100"
bright_yellow = "#484a00"
bright_green = "#6a00b5"
bright_cyan = "#025510"
bright_blue = "#035426"
bright_magenta = "#7e0290"
