mode = "dark"

accent = "#fe4ec3"
selection = "#621e4b"
muted = "#90797f"

background = "#030102"
dark_background = "#020101"
darker_background = "#010001"
lighter_background = "#1e1216"

foreground = "#faf3f5"
dark_foreground = "#b7aaad"
light_foreground = "#e5dbdd"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1ce5f2ee) rgba(fe4ec3ee) 45deg"
hyprland_inactive_border = "rgba(90797faa)"

red = "#ff6558"
yellow = "#fad60b"
orange = "#fea347"
green = "#acd809"
cyan = "#1ce5f2"
blue = "#6f9afe"
magenta = "#fe4ec3"
brown = "#8c5a27"

bright_red = "#feaba0"
bright_yellow = "#ffe887"
bright_green = "#c9fb08"
bright_cyan = "#abf7fe"
bright_blue = "#a9c4fc"
bright_magenta = "#fda3d8"
