mode = "dark"

accent = "#fe42d1"
selection = "#4c143f"
muted = "#725c62"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#12080b"

foreground = "#efe5e7"
dark_foreground = "#948e8f"
light_foreground = "#d3c7ca"
bright_foreground = "#fdf9fa"

hyprland_active_border = "rgba(feba8bee) rgba(fe42d1ee) 45deg"
hyprland_inactive_border = "rgba(725c62aa)"

red = "#fe423e"
yellow = "#ffe795"
orange = "#ffa452"
green = "#00ea7a"
cyan = "#feba8b"
blue = "#1493bb"
magenta = "#fe42d1"
brown = "#805229"

bright_red = "#fd8c80"
bright_yellow = "#fff9e2"
bright_green = "#9cffb8"
bright_cyan = "#ffe6d5"
bright_blue = "#15b5e5"
bright_magenta = "#fe94de"
