mode = "dark"

accent = "#fe4dd2"
selection = "#621e51"
muted = "#90797f"

background = "#030102"
dark_background = "#020101"
darker_background = "#010001"
lighter_background = "#1e1216"

foreground = "#faf3f5"
dark_foreground = "#b7aaad"
light_foreground = "#e5dbdd"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(feba8bee) rgba(fe4dd2ee) 45deg"
hyprland_inactive_border = "rgba(90797faa)"

red = "#ff645b"
yellow = "#fed404"
orange = "#fda24f"
green = "#00ea7a"
cyan = "#feba8b"
blue = "#19aedc"
magenta = "#fe4dd2"
brown = "#8b592b"

bright_red = "#feaba2"
bright_yellow = "#fee796"
bright_green = "#9cffb8"
bright_cyan = "#fde2d0"
bright_blue = "#63d4ff"
bright_magenta = "#fda1e0"
