mode = "light"

accent = "#a3038d"
selection = "#e7bfe3"
muted = "#7e7081"

background = "#fefdff"
dark_background = "#f6eff7"
darker_background = "#e8e2ea"
lighter_background = "#f1e7f4"

foreground = "#100413"
dark_foreground = "#5a525c"
light_foreground = "#322b34"
bright_foreground = "#020103"

hyprland_active_border = "rgba(0c625dee) rgba(a3038dee) 45deg"
hyprland_inactive_border = "rgba(7e7081aa)"

red = "#ad0447"
yellow = "#894305"
orange = "#9f2d1e"
green = "#8201d7"
cyan = "#0c625d"
blue = "#3c35ee"
magenta = "#a3038d"
brown = "#5f1b12"

bright_red = "#91003a"
bright_yellow = "#743701"
bright_green = "#6b00b3"
bright_cyan = "#00504b"
bright_blue = "#3306e1"
bright_magenta = "#870074"
