mode = "dark"

accent = "#dea5f0"
selection = "#563f5f"
muted = "#7f7c9d"

background = "#020106"
dark_background = "#010104"
darker_background = "#010002"
lighter_background = "#161227"

foreground = "#f5f4fa"
dark_foreground = "#adacb7"
light_foreground = "#dedde6"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(69e5feee) rgba(dea5f0ee) 45deg"
hyprland_inactive_border = "rgba(7f7c9daa)"

red = "#f297c1"
yellow = "#ffd07c"
orange = "#fdb39e"
green = "#6be4c3"
cyan = "#69e5fe"
blue = "#98abfd"
magenta = "#dea5f0"
brown = "#8b6257"

bright_red = "#fdc5dd"
bright_yellow = "#ffe4b6"
bright_green = "#a2fde1"
bright_cyan = "#bef2fe"
bright_blue = "#c2cffd"
bright_magenta = "#f2d0fd"
