mode = "light"

accent = "#6646a0"
selection = "#d6d0e7"
muted = "#697878"

background = "#fbfefe"
dark_background = "#eef3f3"
darker_background = "#e1e5e6"
lighter_background = "#e7eced"

foreground = "#020b0c"
dark_foreground = "#49595a"
light_foreground = "#223132"
bright_foreground = "#000202"

hyprland_active_border = "rgba(0d625cee) rgba(6646a0ee) 45deg"
hyprland_inactive_border = "rgba(697878aa)"

red = "#066264"
yellow = "#605802"
orange = "#2d623b"
green = "#066628"
cyan = "#0d625c"
blue = "#035f7f"
magenta = "#6646a0"
brown = "#1b3b23"

bright_red = "#005052"
bright_yellow = "#504904"
bright_green = "#00541e"
bright_cyan = "#03504b"
bright_blue = "#054d68"
bright_magenta = "#563390"
