mode = "dark"

accent = "#fa695d"
selection = "#4b201c"
muted = "#5f6847"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#090d00"

foreground = "#e7e9e0"
dark_foreground = "#8f908b"
light_foreground = "#c9ccc1"
bright_foreground = "#f9fbf7"

hyprland_active_border = "rgba(86ee7cee) rgba(fa695dee) 45deg"
hyprland_inactive_border = "rgba(5f6847aa)"

red = "#a35e01"
yellow = "#ffe47a"
orange = "#d49f3f"
green = "#a7c81f"
cyan = "#86ee7c"
blue = "#0fa143"
magenta = "#fa695d"
brown = "#6a5020"

bright_red = "#bf7f41"
bright_yellow = "#fff9e2"
bright_green = "#cce38f"
bright_cyan = "#d7ffd3"
bright_blue = "#72b87d"
bright_magenta = "#fda296"
