mode = "dark"

accent = "#7f95fe"
selection = "#242d54"
muted = "#4c6585"

background = "#000412"
dark_background = "#00030e"
darker_background = "#000209"
lighter_background = "#041020"

foreground = "#e3e8f0"
dark_foreground = "#9498a2"
light_foreground = "#c4cbd4"
bright_foreground = "#f8fafd"

hyprland_active_border = "rgba(10edf4ee) rgba(7f95feee) 45deg"
hyprland_inactive_border = "rgba(4c6585aa)"

red = "#017ca5"
yellow = "#cfe8fe"
orange = "#7bb1d3"
green = "#01cee7"
cyan = "#10edf4"
blue = "#507ef1"
magenta = "#7f95fe"
brown = "#3e596a"

bright_red = "#269cca"
bright_yellow = "#f3f9ff"
bright_green = "#7bebfe"
bright_cyan = "#cbfdfe"
bright_blue = "#80a3f0"
bright_magenta = "#a8baff"
