mode = "dark"

accent = "#ff4ec3"
selection = "#61204c"
muted = "#538c8b"

background = "#000303"
dark_background = "#000202"
darker_background = "#000101"
lighter_background = "#001b1b"

foreground = "#eff7f7"
dark_foreground = "#a4b1b1"
light_foreground = "#d5e1e0"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1feaccee) rgba(ff4ec3ee) 45deg"
hyprland_inactive_border = "rgba(538c8baa)"

red = "#fd617b"
yellow = "#ffd339"
orange = "#fda166"
green = "#06e984"
cyan = "#1feacc"
blue = "#14b1cb"
magenta = "#ff4ec3"
brown = "#8b5938"

bright_red = "#fea9b1"
bright_yellow = "#ffe79e"
bright_green = "#9bfebd"
bright_cyan = "#99fee9"
bright_blue = "#1edbfa"
bright_magenta = "#fda3d8"
