mode = "dark"

accent = "#ec9dee"
selection = "#5b3c5f"
muted = "#85789f"

background = "#020107"
dark_background = "#010105"
darker_background = "#010003"
lighter_background = "#1a1029"

foreground = "#f6f4fa"
dark_foreground = "#afacb6"
light_foreground = "#dfdce5"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(2debf9ee) rgba(ec9deeee) 45deg"
hyprland_inactive_border = "rgba(85789faa)"

red = "#fb90bf"
yellow = "#f7d560"
orange = "#ffb293"
green = "#44e8c8"
cyan = "#2debf9"
blue = "#aea3ff"
magenta = "#ec9dee"
brown = "#8c6251"

bright_red = "#fec5dc"
bright_yellow = "#fee79c"
bright_green = "#99ffe6"
bright_cyan = "#a9f8ff"
bright_blue = "#cecafe"
bright_magenta = "#ffc9ff"
