mode = "dark"

accent = "#fe5c90"
selection = "#642337"
muted = "#a1726e"

background = "#060000"
dark_background = "#040000"
darker_background = "#020000"
lighter_background = "#290b0a"

foreground = "#faf3f2"
dark_foreground = "#b7aaa9"
light_foreground = "#e6dbda"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(fdc1abee) rgba(fe5c90ee) 45deg"
hyprland_inactive_border = "rgba(a1726eaa)"

red = "#ff6366"
yellow = "#fecda1"
orange = "#fe9f78"
green = "#ff939e"
cyan = "#fdc1ab"
blue = "#ff6837"
magenta = "#fe5c90"
brown = "#8c5742"

bright_red = "#feaba7"
bright_yellow = "#fde2cb"
bright_green = "#fec7cb"
bright_cyan = "#fce1d7"
bright_blue = "#ffad94"
bright_magenta = "#fda8bc"
