mode = "light"

accent = "#af0052"
selection = "#e9bfd3"
muted = "#876f6d"

background = "#fcfefe"
dark_background = "#faefee"
darker_background = "#ede2e0"
lighter_background = "#f6e7e6"

foreground = "#150404"
dark_foreground = "#605150"
light_foreground = "#372a29"
bright_foreground = "#030101"

hyprland_active_border = "rgba(9b3700ee) rgba(af0052ee) 45deg"
hyprland_inactive_border = "rgba(876f6daa)"

red = "#b30126"
yellow = "#814a01"
orange = "#993902"
green = "#b2003c"
cyan = "#9b3700"
blue = "#a03002"
magenta = "#af0052"
brown = "#5c2201"

bright_red = "#93021e"
bright_yellow = "#6b3c00"
bright_green = "#920030"
bright_cyan = "#7e2c01"
bright_blue = "#862500"
bright_magenta = "#8f0242"
