mode = "light"

accent = "#ab0067"
selection = "#e7bfd6"
muted = "#6b796d"

background = "#fbfffb"
dark_background = "#eef4ef"
darker_background = "#e1e6e1"
lighter_background = "#e6eee7"

foreground = "#020c04"
dark_foreground = "#4e594f"
light_foreground = "#273129"
bright_foreground = "#010201"

hyprland_active_border = "rgba(02653cee) rgba(ab0067ee) 45deg"
hyprland_inactive_border = "rgba(6b796daa)"

red = "#b20040"
yellow = "#515e04"
orange = "#804c00"
green = "#03661d"
cyan = "#02653c"
blue = "#056349"
magenta = "#ab0067"
brown = "#4d2e00"

bright_red = "#910133"
bright_yellow = "#414d01"
bright_green = "#045418"
bright_cyan = "#015330"
bright_blue = "#08523c"
bright_magenta = "#8f0055"
