mode = "dark"

accent = "#ff58a9"
selection = "#612340"
muted = "#6b8971"

background = "#000300"
dark_background = "#000200"
darker_background = "#000100"
lighter_background = "#071b0c"

foreground = "#f1f7f2"
dark_foreground = "#a8b1a9"
light_foreground = "#d9e0da"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(1eef96ee) rgba(ff58a9ee) 45deg"
hyprland_inactive_border = "rgba(6b8971aa)"

red = "#ff5f7d"
yellow = "#cae90d"
orange = "#ffa333"
green = "#2aea56"
cyan = "#1eef96"
blue = "#1ab98b"
magenta = "#ff58a9"
brown = "#8c5a1c"

bright_red = "#fea9b2"
bright_yellow = "#dbf946"
bright_green = "#a2ffa8"
bright_cyan = "#a7ffca"
bright_blue = "#17e5ac"
bright_magenta = "#fda6c9"
